<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <AssemblyName>PsfGuard.Nina.Sync</AssemblyName>
    <RootNamespace>PsfGuard.Nina.Sync</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>
</Project>
